directories:
    dataset_root: "/net/ens/am4ip/datasets/project-dataset"
    save_model_path: "./model.pth"
training:
    batch_size: 16
    num_epochs: 1
    loss: "CrossEntropy"
    optimizer: "Adam"
    learning_rate: 0.001