directories:
    save_model_path: "./model.pth"
training:
    batch_size: 16
    num_epochs: 25
    loss: "CrossEntropy"
    optimizer: "Adam"
    learning_rate: 0.001
dataset:
    root: "/net/ens/am4ip/datasets/project-dataset"
    use_general_transforms: False
    sunny_augmentation_prob: 1
    rainy_augmentation_prob: 0
    original_size: [1920, 1080]